In [19]:
import numpy as np
a=[1,2,3,4,5,6]
print(a)
print(type(a))

[1, 2, 3, 4, 5, 6]
<class 'list'>


In [20]:
# creating a numpy array from the list
print(np.array(a))

[1 2 3 4 5 6]


In [21]:
print(type(np.array(a)))

<class 'numpy.ndarray'>


In [22]:
a=[1,2.8,3,4,5.0,6]

In [23]:
print(a)
print(type(a))

[1, 2.8, 3, 4, 5.0, 6]
<class 'list'>


In [24]:
# creating a numpy array from the list
print(np.array(a))
print(type(np.array(a)))

[1.  2.8 3.  4.  5.  6. ]
<class 'numpy.ndarray'>


In [25]:
print(np.array(a,dtype="float64"))

[1.  2.8 3.  4.  5.  6. ]


In [26]:
print(np.array(a,dtype="float16"))

[1.  2.8 3.  4.  5.  6. ]


In [27]:
a=[1,2,3,4,5,6]
np.array([range (i,i+4) for i in a])

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8],
       [6, 7, 8, 9]])

In [29]:
print(np.zeros(5,dtype='int'))

[0 0 0 0 0]


In [30]:
print(np.zeros(5,dtype='complex64'))

[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


In [32]:
# numpy.one(row,col)

In [35]:
print(np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
# numpy.full(row,col)

In [37]:
print(np.full((3,4),200))

[[200 200 200 200]
 [200 200 200 200]
 [200 200 200 200]]


In [41]:
# numpy.random.random
print(np.random.random((3,3)))

[[0.77130404 0.05164031 0.01640587]
 [0.90715614 0.51833708 0.3654545 ]
 [0.54234478 0.27671639 0.85516825]]


In [42]:
print(np.random.random((3,3)))

[[0.08379454 0.55907092 0.50221176]
 [0.24215594 0.44149755 0.61719981]
 [0.75121643 0.61334812 0.96353744]]


In [43]:
print(np.random.random((3,3)))

[[0.51137791 0.03741977 0.07846932]
 [0.97081883 0.56061061 0.08350173]
 [0.64746506 0.21483822 0.55035285]]


In [44]:
# numpy.random.seed()
np.random.seed(0)
print(np.random.random((3,3)))

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]


In [45]:
np.random.seed(0)
print(np.random.random((3,3)))

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]


In [49]:
np.random.seed(0)
print(np.random.random((5)))

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


In [50]:
np.random.seed(2)
print(np.random.random((5)))

[0.4359949  0.02592623 0.54966248 0.43532239 0.4203678 ]


In [51]:
np.random.seed(2)
print(np.random.random((5)))

[0.4359949  0.02592623 0.54966248 0.43532239 0.4203678 ]


In [52]:
# numpy.random.normal()

In [53]:
print(np.random.normal(0,1,(3,3)))

[[-1.07445552 -0.61722311 -1.50100687]
 [ 0.8935898   0.73954567 -1.42356496]
 [-1.11072776  0.08858007 -1.35423054]]


In [57]:
# numpy.eye()
print(np.eye(2))

[[1. 0.]
 [0. 1.]]


In [59]:
# opeartions on array

In [60]:
len(a)

6

In [68]:
#numpy.arange()
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])